### PR TITLE
Added missing ENUMS and New Property for 2022 Fabrication

### PR DESCRIPTION
**Pull request by DyoungMCWI**
##### Objective
Added missing ENUMS (UTF8 & UTF16) for FILEMODE
Added new Seam/Skin Seam GROUP (read-only) property added in 2022 Fabrication,

##### Abstractions
n/a

##### Tests performed
Tested Hight Lighting, Autocomplete popup and hover tooltips 

##### Screen shot
image
image
image

### CODE REVIEW

**Review by JD-Howard — APPROVED** [review]
Looks good Darren, sorry I was preoccupied for a bit. Due to the number of commits you had, I'd suggest you Squash/Merge this.

**Comment by DyoungMCWI** [comment]
I'm confused....again (sorry).  

I made changes that I attempted to submit in PR#29. They're here. 

However, the changes I make in PR#30 are also shown here, in PR#29. I don't get that.

When you look at PR#30, it's missing the changes I did in PR#29. 

How can something I did earlier contain things that were done after? I can see the other way around but not this.

PR#29 - 9 changed files. 
PR#30 - 7 changed files.

IF you look t the first Diff in the changed files for #29, that's the work I did in #29. There was one other change as well. Those don't show up in #30.

In short, #29 looks more "complete" than #30. 

I can understand each having their own separate or #30 having prior as my branch for #30 likely contained the work I'd done for #29. But it doesn't.  Now sure how #29 contains work that wasn't done until #30.

Let me know how to proceed. If need be I can delete both and just redo them, It wasn't that much work provided I remember everything. 

But as it stands, deleting 30 and keeping 29 will be the only way to have a "complete work" unless Git's doing something I'm unaware of. And the changes were indeed done a few weeks apart...it's not like I did all the edits and submitted weeks apart.

**Comment by DyoungMCWI** [comment]
OK, I think I understand...when you look at the changes in #29, it defaults to showing diffs from ALL PR's. 

If you change that to show only the Diff's from PR#29 as shown here....


It looks like this which shows the  changes specific to only #29.



So if I understand properly, approving #29 and #30 are both needed.

Of course I now see some typo's in the remarks so if you wanted to throw me for another look, you could request I fix those in PR29 and I'll have to figure out how to do that without deleting PR29 and redoing everything.

Let me know how you want to proceed. I'm good with whatever. Appreciate your patience with my learning while I try to 'Git' Git.

**Comment by JD-Howard** [comment]
I am going to squash merge this one and then go see if it makes me do a manual diff adjustment on the 30. Hopefully not, but it could since there is overlap.

**Pull request merged**
