### PR TITLE
PCF SKey Changes

### PR DESCRIPTION
**Pull request by DyoungMCWI**
Added PCFSKey Property to ItemStruct object and edited some other SKey related notes w/version of Fabrication they are supported in.

##### Objective
Missing Property PCFSKey was missing. While adding, researched version where it support was added.

##### Abstractions
n/a

##### Tests performed
n/a

##### Screen shot
n/a

### CODE REVIEW

**Comment by JD-Howard** [comment]
@DyoungMCWI , I am confused on whether this PR replaces the previous one. They seem to have a lot of the same changes, but not entirely...

**Comment by DyoungMCWI** [comment]
Maybe I did something wrong then.

The second wasn’t designed to replace the first.

I merely made a new branch and did more work...or so I thought. Maybe I did something wrong and the second PR grabbed the changes of the first too?

Only the PCKSKEY was added in #2 plus a few comment changes.

The first one had added functions related to 2022 but I forget at the moment what.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DyoungMCWI** [comment]
See comments in #29.

**Review by JD-Howard — APPROVED** [review]

**Comment by JD-Howard** [comment]
@DyoungMCWI this isn't saying it has any conflicts so everything is fine. However, do note that this PR was technically better because it was using a branch. You should always create a branch from Upstream/Main, do all your work on that, merge Upstream/Main into your branch (if it has changes) just before you create a pull request. Repeat that entire process if your going to do a second PR on some other set of files. If its the same files, you may as well just add more commits to your 1st PR.

**Pull request merged**
